#!/usr/bin/env python3
"""Correlation-aware exposure control for crypto spot BUY selection.

This is intentionally a market-behaviour proxy rather than a claimed sector
taxonomy: crypto assets do not have a reliable universal sector classification.
"""

from concurrent.futures import ThreadPoolExecutor
from math import sqrt

from botutil import http_json

BN = "https://data-api.binance.vision"


def _returns(coin, interval="1h", limit=72):
    try:
        data = http_json(
            f"{BN}/api/v3/klines?symbol={coin}USDT&interval={interval}&limit={limit}",
            timeout=10,
        )
        closes = [float(k[4]) for k in data[:-1]]
        if len(closes) < 20:
            return None
        return [(b / a - 1.0) for a, b in zip(closes[:-1], closes[1:]) if a > 0]
    except Exception:
        return None


def _corr(a, b):
    n = min(len(a), len(b))
    if n < 20:
        return 0.0
    a, b = a[-n:], b[-n:]
    ma, mb = sum(a) / n, sum(b) / n
    va = sum((x - ma) ** 2 for x in a)
    vb = sum((x - mb) ** 2 for x in b)
    if va <= 0 or vb <= 0:
        return 0.0
    return sum((x - ma) * (y - mb) for x, y in zip(a, b)) / sqrt(va * vb)


def select_diversified(ranked, cfg):
    """Select a daily entry set while preserving ranking priority.

    The first qualified signal is always eligible. Subsequent signals are
    accepted unless they exceed the configured correlation threshold with an
    already selected coin. We never manufacture a trade to fill the budget.
    """
    budget = max(0, min(int(cfg.get("max_trade_entries_per_day", 5)), 5))
    if budget <= 1 or len(ranked) <= 1:
        return ranked[:budget], []

    threshold = float(cfg.get("max_pairwise_correlation", 0.88))
    lookback = int(cfg.get("correlation_lookback_bars", 72))
    interval = str(cfg.get("correlation_interval", "1h"))

    coins = []
    for r in ranked:
        coin = str(r.get("coin", "")).upper()
        if coin and coin not in coins:
            coins.append(coin)

    workers = max(2, min(12, int(cfg.get("correlation_workers", 8))))
    with ThreadPoolExecutor(max_workers=workers) as ex:
        values = list(ex.map(lambda c: (c, _returns(c, interval, lookback)), coins))
    returns = dict(values)

    selected, blocked = [], []
    for candidate in ranked:
        coin = str(candidate.get("coin", "")).upper()
        if not coin:
            continue
        conflicts = []
        for existing in selected:
            other = str(existing.get("coin", "")).upper()
            a, b = returns.get(coin), returns.get(other)
            if a and b and _corr(a, b) >= threshold:
                conflicts.append({"coin": other, "correlation": round(_corr(a, b), 3)})
        if conflicts:
            row = dict(candidate)
            row["exposure_blocked"] = True
            row["exposure_conflicts"] = conflicts
            blocked.append(row)
            continue
        selected.append(candidate)
        if len(selected) >= budget:
            break

    return selected, blocked


def correlation_profile(coin, open_positions, cfg):
    """Measure proposed-coin correlation against currently open SPOT positions.

    This is an execution/risk signal only. It does not remove or downgrade a
    market BUY signal generated by scanner.py.
    """
    coin = str(coin or "").upper()
    open_coins = []
    for p in open_positions or []:
        if p.get("status") != "open":
            continue
        other = str(p.get("coin", "")).upper()
        if other and other != coin and other not in open_coins:
            open_coins.append(other)
    if not coin or not open_coins:
        return {
            "coin": coin,
            "correlated": False,
            "max_correlation": 0.0,
            "avg_correlation": 0.0,
            "conflicts": [],
            "data_available": True,
            "reason": "no_open_correlated_positions",
        }

    threshold = float(cfg.get("max_pairwise_correlation", 0.88))
    lookback = int(cfg.get("correlation_lookback_bars", 72))
    interval = str(cfg.get("correlation_interval", "1h"))
    returns = {coin: _returns(coin, interval, lookback)}
    for other in open_coins:
        returns[other] = _returns(other, interval, lookback)

    correlations = []
    conflicts = []
    for other in open_coins:
        a, b = returns.get(coin), returns.get(other)
        if not a or not b:
            continue
        corr = round(_corr(a, b), 3)
        correlations.append(corr)
        if corr >= threshold:
            conflicts.append({"coin": other, "correlation": corr})

    if not correlations:
        return {
            "coin": coin,
            "correlated": False,
            "max_correlation": 0.0,
            "avg_correlation": 0.0,
            "conflicts": [],
            "data_available": False,
            "reason": "correlation_data_unavailable",
        }

    return {
        "coin": coin,
        "correlated": bool(conflicts),
        "max_correlation": max(correlations),
        "avg_correlation": round(sum(correlations) / len(correlations), 3),
        "conflicts": conflicts,
        "data_available": True,
        "reason": "correlation_threshold_exceeded" if conflicts else "within_correlation_limit",
    }


def assess_candidate(coin, open_positions, cfg):
    """Return bounded portfolio-risk metadata for a proposed SPOT entry.

    Fail-open on missing market data: correlation evidence can inform the
    decision, but a network/data failure must not fabricate a block.
    """
    profile = correlation_profile(coin, open_positions, cfg)
    max_corr = float(profile.get("max_correlation", 0.0) or 0.0)
    threshold = float(cfg.get("max_pairwise_correlation", 0.88))
    hard_block = bool(cfg.get("correlation_risk_hard_block", False))
    blocked = bool(profile.get("correlated")) and hard_block
    profile["risk_action"] = "BLOCK" if blocked else ("REVIEW" if profile.get("correlated") else "ALLOW")
    profile["hard_block_enabled"] = hard_block
    profile["threshold"] = threshold
    profile["risk_note"] = (
        "correlation conflict requires review"
        if profile.get("correlated") and not blocked
        else ("correlation hard limit exceeded" if blocked else "no correlation risk block")
    )
    return profile
